### PR TITLE
Realtime stats page

### PR DESCRIPTION
**Pull request by daoudclarke**
image

### CODE REVIEW

**Comment by ColinEspinas** [comment]
Is this ready to merge @daoudclarke ?

**Comment by daoudclarke** [comment]
It is, but I have a few more stats to add now 😄

I'll add them to this PR

**Comment by daoudclarke** [comment]
@ColinEspinas ok, this is ready to merge now, feel free to review!

**Comment by ColinEspinas** [comment]
> @ColinEspinas ok, this is ready to merge now, feel free to review!

@daoudclarke Could you update your screenshot to reflect the changes you made ?

**Comment by ColinEspinas** [comment]
Code wise this is fine, not very inline with the other page but as we will work on something new soon, I don't see any problem to merge that as a early step to our next goal.

**Comment by daoudclarke** [comment]
> @daoudclarke Could you update your screenshot to reflect the changes you made ?

Done!

**Pull request merged**
